---

- name: Get docker-compose from git
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/{{ VERSION }}/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
